-- MySQL Script generated by MySQL Workbench
-- Sun Oct 24 01:16:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema demo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `demo` ;

-- -----------------------------------------------------
-- Schema demo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demo` DEFAULT CHARACTER SET utf8 ;
USE `demo` ;

-- -----------------------------------------------------
-- Table `demo`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`user` ;

CREATE TABLE IF NOT EXISTS `demo`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `userid_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demo`.`user_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`user_info` ;

CREATE TABLE IF NOT EXISTS `demo`.`user_info` (
  `user_id` INT NOT NULL,
  `real_name` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `bank_account` VARCHAR(45) NOT NULL,
  `birthday` TIMESTAMP NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_info_id__user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `demo`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demo`.`errand_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`errand_type` ;

CREATE TABLE IF NOT EXISTS `demo`.`errand_type` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`type_id`),
  UNIQUE INDEX `errand_type_id_UNIQUE` (`type_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demo`.`errand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`errand` ;

CREATE TABLE IF NOT EXISTS `demo`.`errand` (
  `errand_id` INT NOT NULL AUTO_INCREMENT,
  `errand_type` INT NOT NULL,
  `status` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`errand_id`, `errand_type`),
  INDEX `errand_user_type_id_idx` (`errand_type` ASC) VISIBLE,
  CONSTRAINT `errand_user_type_id`
    FOREIGN KEY (`errand_type`)
    REFERENCES `demo`.`errand_type` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demo`.`delivery_errand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`delivery_errand` ;

CREATE TABLE IF NOT EXISTS `demo`.`delivery_errand` (
  `errand_id` INT NOT NULL,
  `start_time` TIMESTAMP NOT NULL,
  `end_time` TIMESTAMP NOT NULL,
  `departure` VARCHAR(45) NOT NULL,
  `destination` VARCHAR(45) NOT NULL,
  `item_description` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`errand_id`),
  UNIQUE INDEX `errandid_UNIQUE` (`errand_id` ASC) VISIBLE,
  CONSTRAINT `delivery_errand_errand_id`
    FOREIGN KEY (`errand_id`)
    REFERENCES `demo`.`errand` (`errand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demo`.`pet_errand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`pet_errand` ;

CREATE TABLE IF NOT EXISTS `demo`.`pet_errand` (
  `errand_id` INT NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `start_time` TIMESTAMP NOT NULL,
  `end_time` TIMESTAMP NOT NULL,
  `pet_type` VARCHAR(45) NOT NULL,
  `demand` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`errand_id`),
  UNIQUE INDEX `errandid_UNIQUE` (`errand_id` ASC) VISIBLE,
  CONSTRAINT `pet_errand_errand_id`
    FOREIGN KEY (`errand_id`)
    REFERENCES `demo`.`errand` (`errand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demo`.`errand_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`errand_user` ;

CREATE TABLE IF NOT EXISTS `demo`.`errand_user` (
  `user_id` INT NOT NULL,
  `errand_id` INT NOT NULL,
  `state` INT NOT NULL,
  PRIMARY KEY (`user_id`, `errand_id`),
  INDEX `errand_user_errand_id_idx` (`errand_id` ASC) VISIBLE,
  CONSTRAINT `errand_user_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `demo`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `errand_user_errand_id`
    FOREIGN KEY (`errand_id`)
    REFERENCES `demo`.`errand` (`errand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
